Issues/123 navbar & footer 職缺按鈕區分出 使用者/公司
astrocamp/17th-WorkNet pull request #124
Opened 2024-09-12 12:45 UTC by Ellen9543

身分為 [公司] 點擊職缺會可以看該公司的職缺
身分為 [使用者/未登入] 點擊則是看所有的職缺

https://github.com/user-attachments/assets/255ad04e-4498-4a14-b725-3effe8bdc280

2024-09-13 11:14 UTC, RDNNNNN approved these changes

2024-09-13 13:12 UTC, KK-Huang86 commented on apps/jobs/views.py
> +    page_obj = paginate_queryset(request, jobs, 10)
之前分頁的PR就過了，不太確定為什麼這裡會新增

2024-09-13 13:14 UTC, KK-Huang86 approved these changes

2024-09-14 05:57 UTC, RDNNNNN reviewed
剛剛又拉下來測試一次跳出這個問題，已經清過快取，migrate跟migration沒有異常。

<img width="1672" alt="image" src="https://github.com/user-attachments/assets/a84cbab4-1290-4886-804e-afbdf64e62ce">

<img width="1650" alt="image" src="https://github.com/user-attachments/assets/428f0b38-f5f7-4946-967e-4882ba57337f">

2024-09-14 07:05 UTC, Ellen9543 commented on apps/jobs/views.py
> +    page_obj = paginate_queryset(request, jobs, 10)
不曉得 dev 拉下來的沒有這段

2024-09-14 07:47 UTC, KK-Huang86 requested changes
同御登一樣的問題，註冊新公司時會報錯

2024-09-14 12:36 UTC, kait-wu approved these changes

2024-09-14 13:25 UTC, KK-Huang86 approved these changes

2024-09-14 15:45 UTC, Gujiahan approved these changes

2024-09-14 17:52 UTC, merged