Issues/150 權限_套件_一般會員編輯貼文權限
astrocamp/17th-WorkNet pull request #153
Opened 2024-09-16 06:24 UTC by DongOrange

#150 

一般會員
只有自己發的文可以編輯/刪除，無法編輯/刪除其他人的貼文

https://github.com/user-attachments/assets/70d0a308-4180-4a49-b456-cac84ab0d105

2024-09-17 15:12 UTC, KK-Huang86 commented
<img width="1440" alt="截圖 2024-09-17 23 10 01" src="https://github.com/user-attachments/assets/6f7d9276-3032-4bc7-9ffd-27f587e3da9b">

文章裡面還有一顆「修改評論」的按鈕沒有被列入權限的判斷，使得不是該文的發文者仍可以編輯該文，這邊要再麻煩修改

2024-09-17 15:24 UTC, KK-Huang86 commented on apps/posts/templates/posts/index.html
posts/show.html 裡面也藏有一顆「修改評論」的按鈕得設權限

2024-09-17 15:25 UTC, KK-Huang86 requested changes

2024-09-17 15:25 UTC, KK-Huang86 commented on apps/posts/templates/posts/index.html
> +          <a class="text-white btn btn-primary btn-sm" href="{% url 'posts:edit' id=item.post.id %}">編輯</a>
posts/show.html 裡面也藏有一顆「修改評論」的按鈕得設權限

2024-09-17 15:25 UTC, KK-Huang86 commented on apps/posts/templates/posts/index.html
> +          <a class="text-white btn btn-primary btn-sm" href="{% url 'posts:edit' id=item.post.id %}">編輯</a>
如上面的圖～

2024-09-18 04:34 UTC, DongOrange commented on apps/posts/templates/posts/index.html
> +          <a class="text-white btn btn-primary btn-sm" href="{% url 'posts:edit' id=item.post.id %}">編輯</a>
已修改

2024-09-18 06:11 UTC, KK-Huang86 approved these changes

2024-09-18 07:42 UTC, Ellen9543 approved these changes

2024-09-18 09:14 UTC, kait-wu approved these changes

2024-09-18 09:49 UTC, merged